import './globals.css'
import GlobalThemeWrapper from './lib/GlobalThemeWrapper'
import StyledComponentsRegistry from './lib/register'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <GlobalThemeWrapper>
          {children}
          </GlobalThemeWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
